openapi: 3.0.0
info:
  title: Banking App API
  version: 1.0.0
  description: API for banking web app
paths:
  /authentication/signup:
    post:
      summary: User Sign Up
      description: Create a new user
      requestBody:
        description: User sign up details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username for the new user
                password:
                  type: string
                  description: Password for the new user
                email:
                  type: string
                  description: Email for the new user
              required:
                - username
                - password
                - email
      responses:
        "200":
          description: User created successfully
        "400":
          description: User already exists
        "500":
          description: Server error

  /authentication/signin:
    post:
      summary: User Sign In
      description: Authenticate a user and provide a token
      requestBody:
        description: User sign in details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username of the user
                password:
                  type: string
                  description: Password of the user
      responses:
        "200":
          description: Successfully signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authenticated user
        "404":
          description: User not found
        "400":
          description: Invalid credentials
        "403":
          description: User not verified
        "500":
          description: Server error

  /authentication/verify-email:
    get:
      summary: Verify user email
      parameters:
        - name: verifyCode
          in: query
          required: true
          description: Verification code sent to the user's email
          schema:
            type: string
      responses:
        "200":
          description: Email verified successfully, redirecting to sign in
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirect:
                    type: string
                    description: URL to redirect the user to sign in
        "404":
          description: User not found
        "500":
          description: Server error
  /account/:
    post:
      summary: Create a new account
      description: Create a new account for a user
      tags:
        - Accounts
      security:
        - bearerAuth: []
      requestBody:
        description: Account details (initial balance)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                initialBalance:
                  type: number
                  description: initial balance for the new account
              required:
                - initialBalance
      responses:
        "201":
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Account created successfully
                  account:
                    type: object
                    properties:
                      accountNumber:
                        type: string
                        description: The generated account number
                      balance:
                        type: number
                        description: The initial balance of the account
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Failed to create account"
                  error:
                    type: string
                    description: Error message

  /account/balance/{accountNumber}:
    get:
      summary: Get account balance
      description: Get the balance of an account
      tags:
        - Accounts
      security:
        - bearerAuth: []
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Account balance retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: float
                    description: Account balance
        "404":
          description: Account not found or no access to this account
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Account not found or you do not have access to this account"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Failed to fetch balance"

  /user/profile:
    get:
      summary: Get authenticated user's profile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    description: Username of the user
                  email:
                    type: string
                    description: Email of the user
                  phone:
                    type: string
                    description: Phone number of the user
        "404":
          description: User not found
        "500":
          description: Server error
  /user/accounts:
    get:
      summary: Get authenticated user's accounts
      tags:
        - User
        - Accounts
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Accounts retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        accountNumber:
                          type: string
                          description: The user's account number
                        balance:
                          type: number
                          description: Account balance
        "404":
          description: No accounts found for the user
        "500":
          description: Server error
  /transaction/create:
    post:
      summary: Create a new transaction
      tags:
        - Transaction
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                senderAccount:
                  type: string
                  description: ID of the sender account
                receiverAccount:
                  type: string
                  description: ID of the receiver account
                amount:
                  type: number
                  description: Transaction amount
              required:
                - senderAccount
                - receiverAccount
                - amount
      responses:
        "201":
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transaction created successfully
                  transaction:
                    $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid input
        "404":
          description: Sender or receiver account not found
        "500":
          description: Server error

  /transaction/list/{accountId}:
    get:
      summary: Get transactions for a specific account
      tags:
        - Transaction
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The account ID
      responses:
        "200":
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "404":
          description: Account or transactions not found
        "500":
          description: Server error


components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          description: Username of the user
        email:
          type: string
          description: Email of the user
        is_verified:
          type: boolean
          description: Email verification status
        account:
          type: array
          items:
            type: string
          description: List of account IDs associated with the user
      required:
        - username
        - email
    Account:
      type: object
      properties:
        user_id:
          type: string
          description: User ID
        account_number:
          type: string
          description: Account number
        balance:
          type: number
          description: Account balance
      required:
        - user_id
        - account_number
        - balance
    Transaction:
      type: object
      properties:
        senderAccount:
          type: string
          description: ID of the sender account
        receiverAccount:
          type: string
          description: ID of the receiver account
        amount:
          type: number
          description: Transaction amount
        userId:
          type: string
          description: User ID related to the transaction

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
