name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Create test directories and mocks
        run: |
          cd backend
          mkdir -p tests/mocks
          echo "jest.mock('../../services/email', () => ({
            sendVerificationEmail: jest.fn().mockResolvedValue(true),
            generateVerificationCode: jest.fn().mockReturnValue('123456')
          }));" > tests/mocks/emailServices.js

      - name: Create env file
        run: |
          cd backend
          echo "NODE_ENV=test" > .env.test
          echo "MONGODB_URI=mongodb://localhost:27017/test_db" >> .env.test
          echo "EMAIL_HOST=smtp.example.com" >> .env.test
          echo "EMAIL_PORT=587" >> .env.test
          echo "EMAIL_USER=test@example.com" >> .env.test
          echo "EMAIL_PASS=password123" >> .env.test

      - name: Run tests
        run: |
          cd backend
          NODE_ENV=test npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/test_db
